site_name: LangDAO
site_description: Helping people use their language skills to learn, teach, and earn in Web3.
repo_url: https://github.com/aenhsaihan/langdao-ethonline2025
nav:
  - Home: index.md
  - Product:
      - Overview: product/overview.md
      - MVP Scope: product/scope-mvp.md
      - Roadmap: product/roadmap.md
      - Testbed (LatAm): product/testbed-latam.md
  - Tech:
      - Architecture: tech/architecture.md
      - Integrations: tech/integrations.md
  - Research:
      - Assumptions: research/assumptions.md
      - Decisions (ADRs):
          - 0001 - Huddle01 Integration: adr/0001-huddle01.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences # enables ```mermaid fences
